version: '3.8'

services:
  # Development service
  admin-portal-dev:
    build:
      context: .
      target: development
    container_name: admin-portal-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    command: npm run dev -- --host 0.0.0.0
    networks:
      - app-network

  # Nginx development service
  nginx-dev:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin-portal-dev
    networks:
      - app-network

  # Production service
  admin-portal-prod:
    build:
      context: .
      target: production
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    container_name: admin-portal-prod
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
