version: '3.8'

services:
  # Development service
  admin-portal-dev:
    build:
      context: .
      target: development
    container_name: admin-portal-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    command: npm run dev -- --host 0.0.0.0

  # Production service
  admin-portal-prod:
    build:
      context: .
      target: production
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    container_name: admin-portal-prod
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
